### ISSUE TITLE
Functions are not composable: f(x:int):int { x+x } 10+f(10) returns error. Type check is wrong (may return integer, although signature says string).

### ISSUE THREAD

**Issue by onur1211** [onur1211/verse-interpreter#32]

**Comment by MrNobdy-T** [comment]
### When it works
Works if written like this "f(10)+10"


### When it doesnt work
When written like this "10 + f(10)" its interpreted as an array literal

![image](https://github.com/onur1211/verse-interpreter/assets/98278340/0fdd72e9-b9b7-49c2-811f-8b6a0f358823)

**Comment by onur1211** [comment]
Possible solution: Adding an **'array'** keyword to the grammar which is required for creating a collection.

Creating a collection then would look something like this: 

`myArray:=array(1,2,3)`

instead of

`myArray:=(1,2,3)`
